// Serves the repo-root llms-full.txt (generated by scripts/generate-llms.mjs) at <site>/llms-full.txt.
import type { APIRoute } from 'astro';
import content from '../../../llms-full.txt?raw';

export const GET: APIRoute = () => new Response(content, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
