allowBuilds:
  '@parcel/watcher': true
  esbuild: false
  lmdb: true
  msgpackr-extract: true

overrides:
  esbuild: '0.28.0'
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2200.0'
  - '@angular-devkit/core@22.0.0'
  - '@angular-devkit/schematics@22.0.0'
  - '@angular/cli@22.0.0'
  - '@schematics/angular@22.0.0'
  - '@angular/animations@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/build@22.0.0'
  - '@angular/cdk@22.0.0'
  - '@angular/common@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/compiler-cli@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/compiler@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/core@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/forms@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/language-service@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/localize@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/material@22.0.0'
  - '@angular/platform-browser-dynamic@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/platform-browser@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/router@22.0.0 || 22.0.4 || 22.0.8'
  - '@angular/ssr@22.0.0'
  - ng-packagr@22.0.0
  - eslint-plugin-jsdoc@63.0.9
  - prettier@3.8.5
