name: Release

on:
  push:
    branches:
      - master

permissions:
  id-token: write   # Required for npm trusted publishing (OIDC)
  contents: write  # Required for semantic-release to push tags/commits


jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Copy README
        run: cp README.md ./dist/ng-select/

      - name: Semantic release
        run: npx semantic-release

      - name: copy @ng-select/ng-select version to @ng-select/ng-option-highlight
        run: |
          TEMPFILE=$(mktemp)

          jq ".version = $(jq .version ./dist/ng-select/package.json)" \
            ./dist/ng-option-highlight/package.json > "$TEMPFILE"
          mv "$TEMPFILE" ./dist/ng-option-highlight/package.json

      - name: publish @ng-select/ng-option-highlight
        run: pnpm publish ./dist/ng-option-highlight --no-git-checks --provenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build demo
        run: pnpm build:demo

      - name: Deploy demo 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: dist/demo/browser
